### ISSUE TITLE
📣 Masa Bittensor release v0.7

### ISSUE THREAD

**Issue by mudler** [masa-finance/roadmap#33]
### 🌍  Protocol

- [x] https://github.com/masa-finance/masa-bittensor/issues/122
- [x] https://github.com/masa-finance/masa-bittensor/issues/124
- [x] https://github.com/masa-finance/masa-bittensor/issues/123
- [x] https://github.com/masa-finance/issues/issues/197

### 📖 Documentation
- [x] masa-finance/roadmap#52
- [ ] https://github.com/masa-finance/masa-bittensor/issues/139
- [x] https://github.com/masa-finance/masa-bittensor/issues/125
- [x] https://github.com/masa-finance/masa-bittensor/issues/137

###  📡 Production Environment

 - [x] https://github.com/masa-finance/roadmap/issues/20

### :robot: CI && Release process

- [x] https://github.com/masa-finance/masa-bittensor/issues/109
- [ ] masa-finance/roadmap#53
- [x] masa-finance/masa-bittensor#176

### Product

- [x] https://github.com/masa-finance/masa-bittensor/issues/132

## 🔦 Highlights

< top highlights for this release notes >

## ✅ Release Checklist

- [ ] **Stage 0 - Finishing Touches**
    - [ ] Make sure CI tests are passing.
    - [ ] Ensure SDK is aligned to have the neded Oracle features exposed for the release
    - [ ] Ensure the CLI is aligned to consume the latest SDK correctly
    - [ ] There is a Masa-Oracle release
    - [ ] Update release files to bump the version in the Oracle
- [ ] **Stage 1 - Manual testing**
  - How: Using the assets from master, make sure that test scenarios not covered by automatic tests are passing, and that docs are still aligned
    - [ ] ...
- [ ] **Stage 3 - Release**
  - [ ] Tag Oracle
  - [ ] Tag SDK
  - [ ] CLI and App needs to point to SDK version and have its own tag
- [ ] **Stage 4 - After release**
  - [ ] Release notes needs to be updated in the documentation here: https://developers.masa.ai/docs/masa-oracle/RELEASE_NOTES
  - [ ] Update notion documentation about release
