### ISSUE TITLE
[EPIC]: TEE

### ISSUE THREAD

**Issue by Luka-Loncar** [masa-finance/roadmap#87]
- [ ] Container images
- [ ] Docs of the container images - link the existing one from v1.2 release
- [ ] Setup your own testing env 
- [ ] Create client for interfacing with TEE worker (python)
- [ ] Integrate client into subnet 42 code (make sure that data which is circulating over the network is encrypted)
- [ ] Create docker compose file to run the whole stack

**Comment by mudler** [comment]
Closing in favor of https://github.com/masa-finance/roadmap/issues/89
